//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetTexcel_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJeu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblJeu()
        {
            this.tblProjet = new HashSet<tblProjet>();
        }
    
        public int idJeu { get; set; }
        public string developpeur { get; set; }
        public string description { get; set; }
        public string minimalConfig { get; set; }
        public int idClassification { get; set; }
        public int idGenre { get; set; }
        public int idTheme { get; set; }
        public int idPlatform { get; set; }
        public string nom { get; set; }
        public string tag { get; set; }
    
        public virtual tblClassification tblClassification { get; set; }
        public virtual tblGenre tblGenre { get; set; }
        public virtual tblPlatform tblPlatform { get; set; }
        public virtual tblTheme tblTheme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProjet> tblProjet { get; set; }
    }
}
