//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetTexcel_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public string username { get; set; }
        public string pass { get; set; }
        public string matricule { get; set; }
        public byte administre { get; set; }
    
        public virtual tblEmploye tblEmploye { get; set; }
    }
}
