using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Projet_Texcel
{
    public partial class Categorie : Form
    {
        Form1 form;
        bdTexelFredAlexEntities context; //rajouter
        int cptValide = 0;
        public Categorie(Form1 form)
        {
            InitializeComponent();
            this.form = form;
            context = new bdTexelFredAlexEntities();// rajouter
           
        }

        
        private void Categorie_FormClosing(object sender, FormClosingEventArgs e)
        {
            form.cateConn = false;
            this.context.Dispose();// rajouter
        }

        private void bindingNavigatorAddNewItem_Click(object sender, EventArgs e)
        {
            // Save the changes to the database. 
            this.context.SaveChanges();  //rajouter

            // Refresh the controls to show the values         
            // that were generated by the database.
            this.dataGridViewCRUDCateg.Refresh(); // à rajouter avec le nom du datagridview que ta
           
        }
    }
}
