//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Texcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTravail
    {
        public int idTest { get; set; }
        public int idEquipe { get; set; }
        public int idProjet { get; set; }
    
        public virtual tblEquipe tblEquipe { get; set; }
        public virtual tblProjet tblProjet { get; set; }
        public virtual tblTest tblTest { get; set; }
    }
}
